        !COMPILER-GENERATED INTERFACE MODULE: Tue Nov 08 00:07:41 2016
        MODULE PRINTSOLVEDMATRIX__genmod
          INTERFACE 
            SUBROUTINE PRINTSOLVEDMATRIX(DIM,NC,X,Y,Z,OUTPUT)
              INTEGER(KIND=4) :: DIM
              INTEGER(KIND=4) :: NC(100,100)
              INTEGER(KIND=4) :: X(100)
              INTEGER(KIND=4) :: Y(100)
              INTEGER(KIND=4) :: Z
              INTEGER(KIND=4) :: OUTPUT
            END SUBROUTINE PRINTSOLVEDMATRIX
          END INTERFACE 
        END MODULE PRINTSOLVEDMATRIX__genmod
