        !COMPILER-GENERATED INTERFACE MODULE: Wed Jan 11 11:42:35 2017
        MODULE READCOSTMATRIX__genmod
          INTERFACE 
            SUBROUTINE READCOSTMATRIX(COSTFILE,N,COSTMATRIX)
              CHARACTER(LEN=150) :: COSTFILE
              INTEGER(KIND=4) :: N
              INTEGER(KIND=4) :: COSTMATRIX(100,100)
            END SUBROUTINE READCOSTMATRIX
          END INTERFACE 
        END MODULE READCOSTMATRIX__genmod
